"""Upgrade ProductTable

Revision ID: 28f84b1ebfe9
Revises: c4877cf4aa35
Create Date: 2023-12-07 09:56:29.286689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f84b1ebfe9'
down_revision: Union[str, None] = 'c4877cf4aa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(), nullable=True))
    op.add_column('product', sa.Column('variety', sa.String(), nullable=True))
    op.add_column('product', sa.Column('producer', sa.String(), nullable=True))
    op.add_column('product', sa.Column('characteristics', sa.String(), nullable=True))
    op.add_column('product', sa.Column('price', sa.String(), nullable=True))
    op.drop_column('product', 'instrument_type')
    op.drop_column('product', 'figi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('figi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('instrument_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'price')
    op.drop_column('product', 'characteristics')
    op.drop_column('product', 'producer')
    op.drop_column('product', 'variety')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
