"""Upgrade ProductTable3

Revision ID: 570c145a2824
Revises: e6a13804ff0e
Create Date: 2023-12-07 10:11:56.615852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570c145a2824'
down_revision: Union[str, None] = 'e6a13804ff0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'type')
    # ### end Alembic commands ###
