"""Upgrade ProductTable1

Revision ID: 5effeaac4c83
Revises: 28f84b1ebfe9
Create Date: 2023-12-07 09:59:30.667325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5effeaac4c83'
down_revision: Union[str, None] = '28f84b1ebfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('characteristic', sa.String(), nullable=True))
    op.drop_column('product', 'characteristics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('characteristics', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'characteristic')
    # ### end Alembic commands ###
