"""Upgrade ProductTable4

Revision ID: 79f083197ddd
Revises: 570c145a2824
Create Date: 2023-12-07 10:19:27.121570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f083197ddd'
down_revision: Union[str, None] = '570c145a2824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
