"""Upgrade ProductTable2

Revision ID: e6a13804ff0e
Revises: 5effeaac4c83
Create Date: 2023-12-07 10:07:06.779965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a13804ff0e'
down_revision: Union[str, None] = '5effeaac4c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_type', sa.String(), nullable=True))
    op.drop_column('product', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'product_type')
    # ### end Alembic commands ###
