"""Initial

Revision ID: e9b5cd5a5e7e
Revises: fe263192ecf5
Create Date: 2023-12-06 15:08:46.237072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b5cd5a5e7e'
down_revision: Union[str, None] = 'fe263192ecf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
